#!/usr/bin/env python3
"""Prepare release artifacts and a tap formula locally. Never publishes anything.

Requires Python 3.11+. Usage: check-version TAG | package TAG TARGET BINARY OUT |
assemble TAG OUT. Assemble requires all four archives, so partial builds cannot ship.
"""
import argparse
import hashlib
import os
from pathlib import Path
import re
import tarfile
import tomllib

ROOT = Path(__file__).resolve().parents[1]
REPO = "https://github.com/smarzban/herdr-tsk"
TARGETS = (
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
    "aarch64-unknown-linux-musl",
    "x86_64-unknown-linux-musl",
)


def version(tag):
    if not re.fullmatch(r"v[0-9]+\.[0-9]+\.[0-9]+", tag):
        raise ValueError("expected a stable tag such as v1.2.3")
    return tag[1:]


def check_version(tag, manifest=ROOT / "Cargo.toml"):
    wanted = version(tag)
    with Path(manifest).open("rb") as source:
        actual = tomllib.load(source)["package"]["version"]
    if actual != wanted:
        raise ValueError(f"tag {tag} does not match crate version {actual}")


def package(tag, target, binary, out):
    version(tag)
    if target not in TARGETS:
        raise ValueError(f"unsupported target: {target}")
    binary, out = Path(binary), Path(out)
    if not binary.is_file() or not os.access(binary, os.X_OK) or not binary.stat().st_size:
        raise ValueError("binary must be a nonempty executable file")
    out.mkdir(parents=True, exist_ok=True)
    archive = out / f"tsk-{tag}-{target}.tar.gz"
    if archive.exists():
        raise ValueError(f"refusing to replace {archive}")
    with tarfile.open(archive, "x:gz") as bundle:
        for path, name in [(binary, "tsk"), (ROOT / "LICENSE", "LICENSE"), (ROOT / "README.md", "README.md")]:
            info = bundle.gettarinfo(str(path), arcname=name)
            info.uid = info.gid = 0
            info.uname = info.gname = ""
            info.mode = 0o755 if name == "tsk" else 0o644
            with path.open("rb") as data:
                bundle.addfile(info, data)
    return archive


def assemble(tag, out):
    release_version = version(tag)
    out = Path(out)
    archives = [out / f"tsk-{tag}-{target}.tar.gz" for target in TARGETS]
    if any(not path.is_file() for path in archives):
        raise ValueError("all four platform archives are required")
    outputs = [out / name for name in ("install.sh", "SHA256SUMS", "tsk.rb")]
    for path in outputs:
        if os.path.lexists(path):
            raise ValueError(f"refusing to replace {path}")
    digests = {}
    for target, archive in zip(TARGETS, archives):
        with tarfile.open(archive) as bundle:
            members = bundle.getmembers()
            if [m.name for m in members] != ["tsk", "LICENSE", "README.md"] or any(not m.isfile() for m in members):
                raise ValueError(f"unexpected archive contents: {archive}")
            if not members[0].size or members[0].mode != 0o755:
                raise ValueError(f"invalid executable in {archive}")
        digests[target] = hashlib.sha256(archive.read_bytes()).hexdigest()
    installer = (ROOT / "site/public/install.sh").read_bytes()
    installer_digest = hashlib.sha256(installer).hexdigest()
    sums = [f"{digests[target]}  {archive.name}\n" for target, archive in zip(TARGETS, archives)]
    sums.append(f"{installer_digest}  install.sh\n")
    lines = [
        "# Generated by herdr-tsk scripts/release.py. Commit to homebrew-tap/Formula/tsk.rb.",
        "class Tsk < Formula",
        '  desc "A task board for your terminal"',
        '  homepage "https://gettsk.sh"',
        f'  version "{release_version}"',
        '  license "MIT"',
    ]
    for os_name, suffix in [("macos", "apple-darwin"), ("linux", "unknown-linux-musl")]:
        lines.extend(["", f"  on_{os_name} do"])
        for cpu, arch in [("arm", "aarch64"), ("intel", "x86_64")]:
            target = f"{arch}-{suffix}"
            lines.extend([
                f"    on_{cpu} do",
                f'      url "{REPO}/releases/download/{tag}/tsk-{tag}-{target}.tar.gz"',
                f'      sha256 "{digests[target]}"',
                "    end",
            ])
        lines.append("  end")
    lines.extend([
        "", "  def install", '    bin.install "tsk"', "  end", "",
        "  def caveats", '    "To register the shared tsk binary and shortcuts in Herdr, run: tsk setup herdr"', "  end", "",
        "  test do", '    ENV["TSK_STATE_DIR"] = (testpath/"state").to_s',
        '    ENV["TSK_CONFIG_DIR"] = (testpath/"config").to_s',
        '    assert_match "usage: tsk", shell_output("#{bin}/tsk --help")',
        '    system bin/"tsk", "add", "--desk", "-t", "Homebrew smoke"',
        '    assert_match "Homebrew smoke", shell_output("#{bin}/tsk list --desk")',
        "  end", "end", "",
    ])
    for path, content in zip(outputs, [installer, "".join(sums).encode("utf-8"), "\n".join(lines).encode("utf-8")]):
        # Exclusive creation also refuses a file/link introduced after the preflight.
        with path.open("xb") as destination:
            destination.write(content)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    check = commands.add_parser("check-version")
    check.add_argument("tag")
    pack = commands.add_parser("package")
    for name in ["tag", "target", "binary", "out"]:
        pack.add_argument(name)
    gather = commands.add_parser("assemble")
    gather.add_argument("tag")
    gather.add_argument("out")
    args = parser.parse_args()
    try:
        if args.command == "check-version":
            check_version(args.tag)
        elif args.command == "package":
            package(args.tag, args.target, args.binary, args.out)
        else:
            assemble(args.tag, args.out)
    except (ValueError, OSError, tarfile.TarError) as error:
        parser.exit(1, f"release: {error}\n")


if __name__ == "__main__":
    main()
